import Vue from 'vue';
import { 
  Tabbar, 
  TabbarItem, 
  Swipe, 
  SwipeItem, 
  NavBar,
  Icon, 
  Rate,
  Button,
  Toast,
  DropdownMenu,
  DropdownItem,
  Tab,
  Tabs,
  Empty,
  Cell,
  CellGroup,
  Picker,
  Popup,
  DatetimePicker,
  Uploader,
  Area,
  Search,
  Dialog,
  SwitchCell
} from 'vant';
Vue.use(SwitchCell);
Vue.use(Dialog);
Vue.use(Search);
Vue.use(Uploader);
Vue.use(Empty);
Vue.use(Button);
Vue.use(Tabbar);
Vue.use(TabbarItem);
Vue.use(Swipe);
Vue.use(SwipeItem);
Vue.use(NavBar);
Vue.use(Icon);
Vue.use(Rate);
Vue.use(Toast);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Tab);
Vue.use(Tabs);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(Picker);
Vue.use(Popup);
Vue.use(DatetimePicker);
Vue.use(Area);